---
- hosts: test
  gather_facts: True
  become: yes
  vars_files: ../vars/vars.yaml
  tasks:
    # - name: Allow k8s api port 6443
    #   community.general.ufw:
    #     rule: allow
    #     port: '80'
    #     proto: tcp

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: 80
        proto: tcp