---
- hosts: masternode
  gather_facts: True
  become: yes
  vars_files: ../vars/vars.yaml
  tasks:
  #configuring masternode
    # - name: Download networking manifest 
    #   get_url:
    #     url: "{{ calico_config_url}}"
    #     dest: /root/calico.yaml

    # - name: apply calico manifest
    #   shell: kubectl apply -f /root/calico.yaml
    #   register: calico_result

    # - debug: msg="{{ calico_result.stdout }}"

#verify if master node is ready after installing calico
    - name: get master status
      shell: kubectl get nodes | grep master | awk '{ print $2 }'
      register: node_status

    - name: checking master statusy- skipped if master is ready
      fail:
        msg="the master nose is not in ready state"
      when: node_status.stdout != "Ready"

    - debug: msg="master node is ready"