---
- hosts: masternode
  gather_facts: True
  become: yes
  vars_files: ../vars/vars.yaml
  tasks:
  #configuring masternode
    - name: Download calico plugin networking manifest 
      get_url:
        url: "{{ calico_config_url}}"
        dest: "{{ custom_config_dir }}/calico.yaml"

    - name: Apply calico manifest
      shell: kubectl apply -f {{ custom_config_dir }}/calico.yaml
      register: calico_result

    - name: calico installation status
      debug: msg="{{ calico_result.stdout }}"

    - name: Giving a min for master to come up !!!
      pause:
        minutes: 1

#verify if master node is ready after installing calico
    - name: Get master status
      shell: kubectl get nodes | grep master | awk '{ print $2 }'
      register: node_status

    - name: Checking master status- skipped if master is ready
      fail:
        msg="the master nose is not in ready state"
      when: node_status.stdout != "Ready"

    - name: master node status
      debug: msg="master node is ready"