---
- hosts: masternode,workernode
  gather_facts: False
  become: yes
  vars_files: ../vars/vars.yaml
  tasks:
    - name: Copy k8s conf - bridge-nf loader
      copy:
        src: ../files/k8s.conf
        dest: /etc/sysctl.d/k8s.conf
    
    - name: Load br_netfilter
      modprobe:
        name: br_netfilter
        state: present

    - name: validate uuids
      shell: lsmod | grep br_net
      register: netfilter_result

    - name: get currently loaded br netfilter info from kernal
      debug: var=netfilter_result.stdout