---
- hosts: masternode,workernode
  gather_facts: True
  become: yes
  vars_files: ../vars/vars.yaml
  tasks:
#read OS information
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version }}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"

    - name: Install common supporting packages
      apt: name={{ common_k8s_support_packages }} state=present

# Install Packages
    - name: Add an Apt signing key from google
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: configure k8s apt repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        
    - name: Update apt
      apt: update_cache=yes

    - name: install k8s packages
      apt: name={{ common_k8s_packages }} state=present

    - name: setting up apt hold for k8s packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items:
        - "{{ common_k8s_packages }}"

    - name: Just force systemd to reread configs (2.4 and above)
      systemd:
        daemon_reload: yes

    - name: Restart service kubelet
      systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet
