---
- hosts: masternode,workernode
  gather_facts: False
  become: yes
  vars_files: ../vars/vars.yaml
  tasks:
    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"