#this script will shutdown all servers in hosts files
---
- hosts: all
  gather_facts: no
  tasks:
    # - name: Distribution
    #   debug: msg="{{ ansible_distribution }}"

    - name: shutdown
      # command: /sbin/shutdown -h now
      command: /sbin/shutdown -h
      become: yes
      register: shutdown_status
#      sudo: yes

    - name: Shutdown status
      debug: msg=shutdown_status.stdout