---
- hosts: all
  gather_facts: no
  tasks:
    # - name: Distribution
    #   debug: msg="{{ ansible_distribution }}"

    - name: shutdown
      command: /sbin/shutdown -h now
      become: yes
#      sudo: yes

    - name: wait go down
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped