- name: k8s join token for worker
  debug: msg="{{ hostvars['DUMMY_HOST_k8s']['c_token'] }}"

- name: Remove file kubelet conf
  file:
    path: /etc/kubernetes/kubelet.conf 
    state: absent

- name: Remove file ca crt
  file:
    path: /etc/kubernetes/pki/ca.crt 
    state: absent

- name: initiating worker to join
  shell: "{{ hostvars['DUMMY_HOST_k8s']['c_token'] }}"
  register: joined_cluster

- name: worker join status
  debug: msg="{{ joined_cluster.stdout }}"

